version: "3.8"

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./:/app
    command: python -u run_server.py
